const moviesData = [
  {
    _id: '1',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: true,
  },
  {
    _id: '2',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-9.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: true,
  },
  {
    _id: '3',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-2.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '4',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-11.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '5',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-4.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '6',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-6.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '7',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-8.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '8',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-5.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '9',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-7.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '10',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-1.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '11',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-10.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
  {
    _id: '12',
    nameRU: 'В погоне за Бенкси',
    src: '/fotos/pic__COLOR_pic-3.jpg',
    alt: 'В погоне за Бенкси',
    duration: '0ч 42м',
    saved: false,
  },
];

export default moviesData;
